# Generated by Django 4.0.4 on 2022-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('img_class', models.CharField(max_length=256, verbose_name='Класс иконки')),
                ('body', models.CharField(max_length=900, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Деятельность',
            },
        ),
    ]
