# Generated by Django 4.0.4 on 2022-06-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygoal',
            options={'verbose_name': 'Деятельность', 'verbose_name_plural': 'Деятельность'},
        ),
    ]
