# Generated by Django 4.0.4 on 2022-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_companygoal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygoal',
            options={'ordering': ['-pk'], 'verbose_name': 'Деятельность', 'verbose_name_plural': 'Деятельность'},
        ),
        migrations.AddField(
            model_name='companygoal',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный?'),
        ),
    ]
