# Generated by Django 4.0.4 on 2022-06-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_footer_footerlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Подвал меню', 'verbose_name_plural': 'Подвал меню'},
        ),
    ]
