# Generated by Django 4.0.4 on 2022-06-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_footer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vakance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('link', models.CharField(max_length=356, verbose_name='Ссылка')),
                ('active', models.BooleanField(default=False, verbose_name='Активный?')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VakanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('vakance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.vakance')),
            ],
        ),
    ]
