# Generated by Django 4.0.4 on 2022-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_vakance_vakancecriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakance',
            name='salary',
            field=models.CharField(max_length=10, verbose_name='Зарплата'),
        ),
    ]
