# Generated by Django 4.0.4 on 2022-06-12 16:43

import datetime
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('content_short', models.TextField(verbose_name='brief')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('date_added', models.DateTimeField(default=datetime.datetime.today, verbose_name='date added')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('more_text', models.CharField(blank=True, help_text='read more button text', max_length=256, verbose_name='read more')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='news', verbose_name='image')),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': 'news',
                'ordering': ('-date_added',),
                'abstract': False,
            },
        ),
    ]
