# Generated by Django 4.0.4 on 2022-06-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('position', models.SmallIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.ManyToManyField(to='newsapp.tag', verbose_name='tags'),
        ),
    ]
