# Generated by Django 4.0.4 on 2022-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_newcategory_new_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='author',
            field=models.CharField(default=1, max_length=256, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='podr',
            field=models.CharField(default=1, max_length=256, verbose_name='Подразделение'),
            preserve_default=False,
        ),
    ]
