# Generated by Django 4.0.4 on 2022-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_new_author_new_podr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=80, verbose_name='Ник проверяющего')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='Одобрено')),
                ('denied', models.BooleanField(blank=True, null=True, verbose_name='Отказано')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('pay', models.CharField(blank=True, max_length=30, null=True, verbose_name='Выплата')),
            ],
            options={
                'verbose_name': 'Проверка управляющего',
            },
        ),
    ]
