# Generated by Django 4.0.4 on 2022-06-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_managercheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='managercheck',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='newsapp.new'),
        ),
    ]
