# Generated by Django 4.0.4 on 2022-06-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_managercheck_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managercheck',
            name='denied',
        ),
    ]
