# Generated by Django 4.0.4 on 2022-06-19 19:32

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_remove_managercheck_denied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='news', verbose_name='image'),
        ),
    ]
